version: '3.8'

services:
  # Servicio para el backend de Node.js
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://redis:6379
      - SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID}
      - SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET}
      - SPOTIFY_REDIRECT_URI=${SPOTIFY_REDIRECT_URI}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./backend/logs:/app/logs
    networks:
      - spotify-assistant-network

  # Servicio para Redis (caché y sesiones)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - spotify-assistant-network

  # Descomenta si decides añadir MongoDB más adelante
  # mongodb:
  #   image: mongo:6
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb-data:/data/db
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
  #     - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  #   restart: unless-stopped
  #   networks:
  #     - spotify-assistant-network

networks:
  spotify-assistant-network:
    driver: bridge

volumes:
  redis-data:
  # mongodb-data:
